//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: vnarpc.proto

package com.synclient.grpc

@kotlin.jvm.JvmSynthetic
inline fun emptyMessage(block: com.synclient.grpc.EmptyMessageKt.Dsl.() -> kotlin.Unit): com.synclient.grpc.Vnarpc.EmptyMessage =
    com.synclient.grpc.EmptyMessageKt.Dsl._create(com.synclient.grpc.Vnarpc.EmptyMessage.newBuilder())
        .apply { block() }._build()

object EmptyMessageKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    class Dsl private constructor(
        private val _builder: com.synclient.grpc.Vnarpc.EmptyMessage.Builder
    ) {
        companion object {
            @kotlin.jvm.JvmSynthetic
            @kotlin.PublishedApi
            internal fun _create(builder: com.synclient.grpc.Vnarpc.EmptyMessage.Builder): Dsl =
                Dsl(builder)
        }

        @kotlin.jvm.JvmSynthetic
        @kotlin.PublishedApi
        internal fun _build(): com.synclient.grpc.Vnarpc.EmptyMessage = _builder.build()
    }
}

@kotlin.jvm.JvmSynthetic
inline fun com.synclient.grpc.Vnarpc.EmptyMessage.copy(block: com.synclient.grpc.EmptyMessageKt.Dsl.() -> kotlin.Unit): com.synclient.grpc.Vnarpc.EmptyMessage =
    com.synclient.grpc.EmptyMessageKt.Dsl._create(this.toBuilder()).apply { block() }._build()
