//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: vnarpc.proto

package com.synclient.grpc

@kotlin.jvm.JvmSynthetic
inline fun portStatus(block: com.synclient.grpc.PortStatusKt.Dsl.() -> kotlin.Unit): com.synclient.grpc.Vnarpc.PortStatus =
    com.synclient.grpc.PortStatusKt.Dsl._create(com.synclient.grpc.Vnarpc.PortStatus.newBuilder())
        .apply { block() }._build()

object PortStatusKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    class Dsl private constructor(
        private val _builder: com.synclient.grpc.Vnarpc.PortStatus.Builder
    ) {
        companion object {
            @kotlin.jvm.JvmSynthetic
            @kotlin.PublishedApi
            internal fun _create(builder: com.synclient.grpc.Vnarpc.PortStatus.Builder): Dsl =
                Dsl(builder)
        }

        @kotlin.jvm.JvmSynthetic
        @kotlin.PublishedApi
        internal fun _build(): com.synclient.grpc.Vnarpc.PortStatus = _builder.build()

        /**
         * <code>bool open = 1;</code>
         */
        var open: kotlin.Boolean
            @JvmName("getOpen")
            get() = _builder.open
            @JvmName("setOpen")
            set(value) {
                _builder.open = value
            }

        /**
         * <code>bool open = 1;</code>
         */
        fun clearOpen() {
            _builder.clearOpen()
        }

        /**
         * <code>bool short = 2;</code>
         */
        var short: kotlin.Boolean
            @JvmName("getShort")
            get() = _builder.short
            @JvmName("setShort")
            set(value) {
                _builder.short = value
            }

        /**
         * <code>bool short = 2;</code>
         */
        fun clearShort() {
            _builder.clearShort()
        }

        /**
         * <code>bool load = 3;</code>
         */
        var load: kotlin.Boolean
            @JvmName("getLoad")
            get() = _builder.load
            @JvmName("setLoad")
            set(value) {
                _builder.load = value
            }

        /**
         * <code>bool load = 3;</code>
         */
        fun clearLoad() {
            _builder.clearLoad()
        }

        /**
         * <code>bool gender = 4;</code>
         */
        var gender: kotlin.Boolean
            @JvmName("getGender")
            get() = _builder.gender
            @JvmName("setGender")
            set(value) {
                _builder.gender = value
            }

        /**
         * <code>bool gender = 4;</code>
         */
        fun clearGender() {
            _builder.clearGender()
        }
    }
}

@kotlin.jvm.JvmSynthetic
inline fun com.synclient.grpc.Vnarpc.PortStatus.copy(block: com.synclient.grpc.PortStatusKt.Dsl.() -> kotlin.Unit): com.synclient.grpc.Vnarpc.PortStatus =
    com.synclient.grpc.PortStatusKt.Dsl._create(this.toBuilder()).apply { block() }._build()
