//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: vnarpc.proto

package com.synclient.grpc;

@kotlin.jvm.JvmSynthetic
public inline fun portStatus(block: com.synclient.grpc.PortStatusKt.Dsl.() -> kotlin.Unit): com.synclient.grpc.Vnarpc.PortStatus =
  com.synclient.grpc.PortStatusKt.Dsl._create(com.synclient.grpc.Vnarpc.PortStatus.newBuilder()).apply { block() }._build()
public object PortStatusKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.synclient.grpc.Vnarpc.PortStatus.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.synclient.grpc.Vnarpc.PortStatus.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.synclient.grpc.Vnarpc.PortStatus = _builder.build()

    /**
     * <code>bool open = 1;</code>
     */
    public var open: kotlin.Boolean
      @JvmName("getOpen")
      get() = _builder.getOpen()
      @JvmName("setOpen")
      set(value) {
        _builder.setOpen(value)
      }
    /**
     * <code>bool open = 1;</code>
     */
    public fun clearOpen() {
      _builder.clearOpen()
    }

    /**
     * <code>bool short = 2;</code>
     */
    public var short: kotlin.Boolean
      @JvmName("getShort")
      get() = _builder.getShort()
      @JvmName("setShort")
      set(value) {
        _builder.setShort(value)
      }
    /**
     * <code>bool short = 2;</code>
     */
    public fun clearShort() {
      _builder.clearShort()
    }

    /**
     * <code>bool load = 3;</code>
     */
    public var load: kotlin.Boolean
      @JvmName("getLoad")
      get() = _builder.getLoad()
      @JvmName("setLoad")
      set(value) {
        _builder.setLoad(value)
      }
    /**
     * <code>bool load = 3;</code>
     */
    public fun clearLoad() {
      _builder.clearLoad()
    }

    /**
     * <code>bool gender = 4;</code>
     */
    public var gender: kotlin.Boolean
      @JvmName("getGender")
      get() = _builder.getGender()
      @JvmName("setGender")
      set(value) {
        _builder.setGender(value)
      }
    /**
     * <code>bool gender = 4;</code>
     */
    public fun clearGender() {
      _builder.clearGender()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.synclient.grpc.Vnarpc.PortStatus.copy(block: com.synclient.grpc.PortStatusKt.Dsl.() -> kotlin.Unit): com.synclient.grpc.Vnarpc.PortStatus =
  com.synclient.grpc.PortStatusKt.Dsl._create(this.toBuilder()).apply { block() }._build()
